#!/usr/bin/env python3
"""
MVPScopeAgent - MVP 范围定义 agent

职责：
- 基于问题定义，压缩出第一版可交付范围
- 明确 must-have / nice-to-have / out-of-scope
- 写出验收标准

输出：
- mvp_scope.md
- mvp_scope.json
"""

import json
from typing import Any, Dict
from agents import AgentBase


class MVPScopeAgent(AgentBase):
    AGENT_NAME = "MVPScopeAgent"
    STAGE_NAME = "mvp_scope"
    ROLE_DESCRIPTION = "范围管理专家，擅长压缩需求到最小可交付范围"
    
    INPUT_FILES = ["structured_problem_definition.json"]
    OUTPUT_FILES = ["mvp_scope.md", "mvp_scope.json"]
    
    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        problem_def = input_data.get("structured_problem_definition", {})
        
        # 定义 MVP 范围
        scope = self._define_mvp_scope(problem_def)
        
        # 生成 markdown 报告
        md_content = self._generate_markdown(scope)
        
        return {
            "mvp_scope.md": md_content,
            "mvp_scope.json": scope  # JSON 输出
        }
    
    def _define_mvp_scope(self, problem_def: Dict) -> Dict:
        """定义 MVP 范围"""
        return {
            "must_have": [
                "核心功能：用户上传 Excel 文件",
                "核心功能：自动识别企业主体",
                "核心功能：生成 entity 清单",
                "核心功能：调用查册接口",
                "核心功能：返回结构化结果",
                "核心功能：支持人工复核",
                "核心功能：支持导出结果"
            ],
            "nice_to_have": [
                "批量处理优化",
                "结果预览功能",
                "简单的统计信息"
            ],
            "out_of_scope": [
                "用户登录和权限系统",
                "复杂报表功能",
                "多租户支持",
                "移动端适配"
            ],
            "acceptance_criteria": [
                "用户上传 Excel 后，系统能在 30 秒内完成识别",
                "识别准确率 > 90%",
                "查册接口调用成功率 > 95%",
                "人工复核界面可在 1 分钟内完成单个企业审核",
                "导出功能支持 CSV 和 Excel 格式"
            ],
            "constraints": [
                "第一版仅支持 Web 端",
                "仅支持 Excel 格式输入",
                "单次处理上限：1000 条记录"
            ],
            "timeline_estimate": "2-3 周 MVP"
        }
    
    def _generate_markdown(self, scope: Dict) -> str:
        """生成 markdown 格式的范围定义"""
        md = f"""# MVP 范围定义

## Must-Have（必须有）
{chr(10).join(f'- [ ] {item}' for item in scope['must_have'])}

## Nice-to-Have（最好有）
{chr(10).join(f'- [ ] {item}' for item in scope['nice_to_have'])}

## Out-of-Scope（不在范围内）
{chr(10).join(f'- [x] {item}' for item in scope['out_of_scope'])}

## 验收标准
{chr(10).join(f'- [ ] {criteria}' for criteria in scope['acceptance_criteria'])}

## 约束条件
{chr(10).join(f'- {c}' for c in scope['constraints'])}

## 时间估算
{scope['timeline_estimate']}

---
*Generated by MVPScopeAgent*
"""
        return md


if __name__ == "__main__":
    agent = MVPScopeAgent("/home/admin/openclaw/workspace")
    test_input = {"structured_problem_definition": {"target_users": ["合规分析员"]}}
    result = agent.run(test_input)
    print(f"Generated files: {result}")
