#!/usr/bin/env python3
"""
抖音热点捕捉定时任务

功能：
1. 每天扫描热点
2. 筛选知识类话题
3. 生成选题报告
4. 保存到本地

运行方式：
- 手动：python3 tasks/douyin_trend_capture.py
- 定时：配置 cron，每天执行一次
"""

import sys
from pathlib import Path
from datetime import datetime

# 添加父目录到路径
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.trend_hunter.agent import TrendHunterAgent


def capture_trends():
    """执行热点捕捉"""
    
    print("="*60)
    print("🔍 抖音热点捕捉任务")
    print("="*60)
    print(f"执行时间：{datetime.now().isoformat()}")
    
    # 创建热点发现 Agent
    agent = TrendHunterAgent("/home/admin/openclaw/workspace")
    
    # 执行热点扫描
    result = agent.execute({
        "platforms": ["weibo", "zhihu", "douyin", "bilibili"],
        "category": "all",
        "limit": 20
    })
    
    # 筛选知识类话题
    knowledge_topics = []
    
    for rec in result["recommendations"]:
        # 知识类关键词
        knowledge_keywords = [
            "知识", "学习", "教程", "技巧", "方法",
            "如何", "怎么", "为什么", "科普", "教育",
            "AI", "工具", "效率", "工作", "成长"
        ]
        
        title = rec.get("topic", "").lower()
        if any(kw in title for kw in knowledge_keywords):
            rec["category"] = "knowledge"
            knowledge_topics.append(rec)
    
    # 生成报告
    report = {
        "captured_at": datetime.now().isoformat(),
        "total_trends": result["report"]["summary"]["total_trends"],
        "knowledge_topics_count": len(knowledge_topics),
        "knowledge_topics": knowledge_topics[:10],  # 只保留前 10 个
        "top_recommendation": knowledge_topics[0] if knowledge_topics else None,
        "platforms_scanned": result["report"]["summary"]["platforms_scanned"]
    }
    
    # 保存报告
    date_str = datetime.now().strftime("%Y%m%d")
    report_dir = Path("/home/admin/openclaw/workspace/artifacts/trend_reports")
    report_dir.mkdir(parents=True, exist_ok=True)
    
    report_file = report_dir / f"{date_str}_douyin_trend_report.json"
    
    import json
    with open(report_file, 'w', encoding='utf-8') as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    
    # 生成 Markdown 版本
    md_file = report_dir / f"{date_str}_douyin_trend_report.md"
    with open(md_file, 'w', encoding='utf-8') as f:
        f.write(generate_markdown_report(report))
    
    print(f"\n✅ 热点捕捉完成")
    print(f"📊 总热点数：{report['total_trends']}")
    print(f"📚 知识类话题：{report['knowledge_topics_count']}")
    print(f"📁 报告保存：{report_file}")
    print(f"📄 Markdown: {md_file}")
    
    return report


def generate_markdown_report(report):
    """生成 Markdown 格式报告"""
    
    md = f"""# 抖音热点捕捉报告

**捕捉时间**: {report['captured_at']}  
**扫描平台**: {report['platforms_scanned']}个  
**总热点数**: {report['total_trends']}  
**知识类话题**: {report['knowledge_topics_count']}个

---

## 🎯 首选推荐

"""
    
    if report.get("top_recommendation"):
        top = report["top_recommendation"]
        md += f"""
### {top['topic']}

- **优先级**: {top.get('priority', 'N/A')}
- **热度**: {top.get('heat_score', 0)}
- **价值**: {top.get('topic_value', 0)}
- **关键词**: {', '.join(top.get('keywords', []))}
- **原因**: {top.get('reason', 'N/A')}
- **建议格式**: {', '.join(top.get('suggested_formats', []))}

"""
    
    md += """
---

## 📚 知识类话题 TOP10

"""
    
    for i, topic in enumerate(report["knowledge_topics"][:10], 1):
        md += f"""
### {i}. {topic['topic']}

- **优先级**: {topic.get('priority', 'N/A')}
- **热度**: {topic.get('heat_score', 0)}
- **关键词**: {', '.join(topic.get('keywords', []))}
- **原因**: {topic.get('reason', 'N/A')}

"""
    
    md += """
---

## 📝 下一步行动

1. 选择首选推荐话题
2. 使用 ContentCreator 生成内容
3. 使用 VideoProducer 制作视频
4. 发布到抖音

---

*Generated by TrendHunter Agent*
"""
    
    return md


if __name__ == "__main__":
    report = capture_trends()
