#!/usr/bin/env python3
"""
ContextPackAgent - 上下文打包 agent

职责：
- 将项目信息整理成后续工程实现可复用的任务包
- 包括目标、技术栈、资源、约束、禁止事项、建议开发顺序

输出：
- context_pack.md
- context_pack.json
"""

import json
from typing import Any, Dict
from agents import AgentBase


class ContextPackAgent(AgentBase):
    AGENT_NAME = "ContextPackAgent"
    STAGE_NAME = "context_pack"
    ROLE_DESCRIPTION = "技术规划专家，擅长整理项目上下文并给出技术建议"
    
    INPUT_FILES = ["mvp_scope.json"]
    OUTPUT_FILES = ["context_pack.md", "context_pack.json"]
    
    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        mvp_scope = input_data.get("mvp_scope", {})
        
        # 生成上下文包
        context_pack = self._generate_context_pack(mvp_scope)
        
        # 生成 markdown 报告
        md_content = self._generate_markdown(context_pack)
        
        return {
            "context_pack.md": md_content,
            "context_pack.json": context_pack
        }
    
    def _generate_context_pack(self, mvp_scope: Dict) -> Dict:
        """生成上下文包"""
        return {
            "project_goals": [
                "实现 Excel 上传和企业自动识别",
                "完成查册接口集成",
                "提供人工复核和导出功能"
            ],
            "recommended_tech_stack": {
                "frontend": ["React", "TypeScript", "TailwindCSS"],
                "backend": ["Python", "FastAPI"],
                "database": ["SQLite (MVP)", "PostgreSQL (production)"],
                "deployment": ["Docker", "Docker Compose"]
            },
            "resources_needed": [
                "查册 API 访问权限",
                "Excel 解析库（pandas / openpyxl）",
                "前端 UI 组件库"
            ],
            "constraints": mvp_scope.get("constraints", []),
            "forbidden_practices": [
                "不要在 MVP 阶段引入复杂的权限系统",
                "不要过度优化性能（先保证功能可用）",
                "不要一次性支持所有 Excel 格式变体"
            ],
            "recommended_order": [
                "1. 搭建项目骨架",
                "2. 实现 Excel 上传和解析",
                "3. 实现企业识别逻辑",
                "4. 集成查册接口",
                "5. 实现人工复核界面",
                "6. 实现导出功能",
                "7. 端到端测试"
            ],
            "key_decisions": [
                "技术栈选择",
                "查册接口供应商",
                "部署环境"
            ]
        }
    
    def _generate_markdown(self, context_pack: Dict) -> str:
        """生成 markdown 格式"""
        md = f"""# 上下文任务包

## 项目目标
{chr(10).join(f'- {g}' for g in context_pack['project_goals'])}

## 推荐技术栈
- Frontend: {', '.join(context_pack['recommended_tech_stack']['frontend'])}
- Backend: {', '.join(context_pack['recommended_tech_stack']['backend'])}
- Database: {', '.join(context_pack['recommended_tech_stack']['database'])}
- Deployment: {', '.join(context_pack['recommended_tech_stack']['deployment'])}

## 所需资源
{chr(10).join(f'- {r}' for r in context_pack['resources_needed'])}

## 约束条件
{chr(10).join(f'- {c}' for c in context_pack['constraints'])}

## 禁止事项
{chr(10).join(f'- ⛔ {f}' for f in context_pack['forbidden_practices'])}

## 建议开发顺序
{chr(10).join(f'- {s}' for s in context_pack['recommended_order'])}

## 关键决策点
{chr(10).join(f'- {d}' for d in context_pack['key_decisions'])}

---
*Generated by ContextPackAgent*
"""
        return md


if __name__ == "__main__":
    agent = ContextPackAgent("/home/admin/openclaw/workspace")
    result = agent.run({})
    print(f"Generated files: {result}")
