#!/usr/bin/env python3
"""
ProblemDefinitionAgent - 问题定义 agent

职责：
- 根据用户输入的项目背景，提炼目标用户、核心问题、使用场景
- 现有替代方案、优先级理由

输出：
- problem_definition.md
- structured_problem_definition.json
"""

import json
from typing import Any, Dict
from agents import AgentBase


class ProblemDefinitionAgent(AgentBase):
    AGENT_NAME = "ProblemDefinitionAgent"
    STAGE_NAME = "problem_definition"
    ROLE_DESCRIPTION = "问题分析专家，擅长从模糊的项目想法中提炼出清晰的问题定义"
    
    INPUT_FILES = ["raw_brief.md"]
    OUTPUT_FILES = ["problem_definition.md", "structured_problem_definition.json"]
    
    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        raw_brief = input_data.get("raw_brief", "")
        
        # 分析问题定义
        analysis = self._analyze_problem(raw_brief)
        
        # 生成 markdown 报告
        md_content = self._generate_markdown(analysis)
        
        # 生成结构化 JSON
        json_content = analysis
        
        return {
            "problem_definition.md": md_content,
            "structured_problem_definition.json": json_content
        }
    
    def _analyze_problem(self, raw_brief: str) -> Dict:
        """分析问题，提取关键要素"""
        # 这里使用简化的启发式分析
        # 实际实现可以调用 LLM
        
        lines = raw_brief.strip().split('\n')
        
        # 提取关键词（简化实现）
        target_users = self._extract_target_users(raw_brief)
        core_problem = self._extract_core_problem(raw_brief)
        use_scenarios = self._extract_use_scenarios(raw_brief)
        alternatives = self._extract_alternatives(raw_brief)
        priority_reason = self._extract_priority_reason(raw_brief)
        
        return {
            "target_users": target_users,
            "core_problem": core_problem,
            "use_scenarios": use_scenarios,
            "existing_alternatives": alternatives,
            "priority_reason": priority_reason,
            "success_criteria": self._define_success_criteria(raw_brief),
            "assumptions": self._list_assumptions(raw_brief),
            "risks": self._identify_risks(raw_brief)
        }
    
    def _extract_target_users(self, brief: str) -> list:
        """提取目标用户"""
        # 简化实现：查找关键词
        keywords = ["用户", "客户", "团队", "企业", "个人", "管理员"]
        users = []
        for kw in keywords:
            if kw in brief:
                users.append(f"使用{kw}的群体")
        return users if users else ["未明确指定的目标用户"]
    
    def _extract_core_problem(self, brief: str) -> str:
        """提取核心问题"""
        # 简化实现：返回输入的摘要
        return brief[:200] + "..." if len(brief) > 200 else brief
    
    def _extract_use_scenarios(self, brief: str) -> list:
        """提取使用场景"""
        return ["主要使用场景待细化", "次要使用场景待细化"]
    
    def _extract_alternatives(self, brief: str) -> list:
        """提取现有替代方案"""
        return ["手工处理", "现有工具（待调研）"]
    
    def _extract_priority_reason(self, brief: str) -> str:
        """提取优先级理由"""
        return "基于用户需求的紧迫性和市场机会"
    
    def _define_success_criteria(self, brief: str) -> list:
        """定义成功标准"""
        return [
            "核心功能可正常运行",
            "目标用户可完成关键任务",
            "性能满足基本要求"
        ]
    
    def _list_assumptions(self, brief: str) -> list:
        """列出假设"""
        return [
            "用户具备基本技术能力",
            "所需外部服务可用"
        ]
    
    def _identify_risks(self, brief: str) -> list:
        """识别风险"""
        return [
            "需求理解偏差",
            "技术实现复杂度被低估"
        ]
    
    def _generate_markdown(self, analysis: Dict) -> str:
        """生成 markdown 格式的问题定义报告"""
        md = f"""# 问题定义报告

## 目标用户
{chr(10).join(f'- {u}' for u in analysis['target_users'])}

## 核心问题
{analysis['core_problem']}

## 使用场景
{chr(10).join(f'- {s}' for s in analysis['use_scenarios'])}

## 现有替代方案
{chr(10).join(f'- {a}' for a in analysis['existing_alternatives'])}

## 优先级理由
{analysis['priority_reason']}

## 成功标准
{chr(10).join(f'- {c}' for c in analysis['success_criteria'])}

## 假设条件
{chr(10).join(f'- {a}' for a in analysis['assumptions'])}

## 潜在风险
{chr(10).join(f'- {r}' for r in analysis['risks'])}

---
*Generated by ProblemDefinitionAgent*
"""
        return md


if __name__ == "__main__":
    # 测试样例
    import sys
    agent = ProblemDefinitionAgent("/home/admin/openclaw/workspace")
    
    test_brief = """
    做一个面向合规分析员的企业批量查册原型系统。
    用户上传来源复杂、字段混乱的 Excel，系统自动识别企业主体并生成 entity 清单，
    再调用查册接口返回结构化结果，支持人工复核和导出。
    第一版不做登录权限和复杂报表。
    """
    
    result = agent.run({"raw_brief": test_brief})
    print(f"Generated files: {result}")
