#!/usr/bin/env python3
"""
QualityCorrectionAgent - 质量校正 agent

职责：
- 基于测试样本、失败案例、日志或当前实现，归纳问题
- 给出最小修复方案，而不是整体推翻重构

输出：
- issue_analysis.md
- fix_plan.json
"""

import json
from typing import Any, Dict
from agents import AgentBase


class QualityCorrectionAgent(AgentBase):
    AGENT_NAME = "QualityCorrectionAgent"
    STAGE_NAME = "quality_correction"
    ROLE_DESCRIPTION = "质量保障专家，擅长识别问题并给出最小修复方案"
    
    INPUT_FILES = ["implementation_plan.md", "test_results.json"]
    OUTPUT_FILES = ["issue_analysis.md", "fix_plan.json"]
    
    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        # 分析问题（简化实现）
        issues = self._analyze_issues(input_data)
        
        # 生成修复计划
        fix_plan = self._generate_fix_plan(issues)
        
        # 生成 markdown 报告
        md_content = self._generate_markdown(issues, fix_plan)
        
        return {
            "issue_analysis": md_content,
            "fix_plan": fix_plan
        }
    
    def _analyze_issues(self, input_data: Dict) -> Dict:
        """分析问题"""
        return {
            "critical": [
                {
                    "id": "CRIT-001",
                    "title": "Excel 解析失败率过高",
                    "description": "当 Excel 包含合并单元格时解析失败",
                    "impact": "高",
                    "repro_rate": "80%"
                }
            ],
            "high": [
                {
                    "id": "HIGH-001",
                    "title": "企业识别准确率低",
                    "description": "对于非标准格式的企业名称识别不准确",
                    "impact": "高",
                    "repro_rate": "60%"
                }
            ],
            "medium": [
                {
                    "id": "MED-001",
                    "title": "导出功能缺少进度提示",
                    "description": "大数据量导出时用户不知道进度",
                    "impact": "中",
                    "repro_rate": "100%"
                }
            ],
            "low": [
                {
                    "id": "LOW-001",
                    "title": "界面缺少空状态提示",
                    "description": "列表为空时没有友好提示",
                    "impact": "低",
                    "repro_rate": "100%"
                }
            ]
        }
    
    def _generate_fix_plan(self, issues: Dict) -> Dict:
        """生成修复计划"""
        fixes = []
        
        for issue in issues.get("critical", []):
            fixes.append({
                "issue_id": issue["id"],
                "priority": 1,
                "action": f"修复：{issue['title']}",
                "approach": "最小改动，不重构",
                "estimate": "2-4 小时",
                "test_required": True
            })
        
        for issue in issues.get("high", []):
            fixes.append({
                "issue_id": issue["id"],
                "priority": 2,
                "action": f"优化：{issue['title']}",
                "approach": "增强识别算法",
                "estimate": "4-8 小时",
                "test_required": True
            })
        
        return {
            "fixes": fixes,
            "total_estimate": "1-2 天",
            "recommendation": "优先修复 critical 和 high 级别问题"
        }
    
    def _generate_markdown(self, issues: Dict, fix_plan: Dict) -> str:
        """生成 markdown 格式"""
        def issue_list(category, items):
            if not items:
                return ""
            return f"\n### {category}\n" + '\n'.join(
                f"- **{i['id']}**: {i['title']} (影响：{i['impact']}, 复现率：{i['repro_rate']})"
                for i in items
            )
        
        md = f"""# 问题分析报告

## 问题汇总

{issue_list('🔴 Critical', issues.get('critical', []))}
{issue_list('🟠 High', issues.get('high', []))}
{issue_list('🟡 Medium', issues.get('medium', []))}
{issue_list('🟢 Low', issues.get('low', []))}

## 修复计划

| 优先级 | 问题 ID | 行动 | 估算 |
|--------|---------|------|------|
{chr(10).join(f"| {f['priority']} | {f['issue_id']} | {f['action']} | {f['estimate']} |" for f in fix_plan['fixes'])}

## 建议

{fix_plan['recommendation']}

---
*Generated by QualityCorrectionAgent*
"""
        return md


if __name__ == "__main__":
    agent = QualityCorrectionAgent("/home/admin/openclaw/workspace")
    result = agent.run({})
    print(f"Generated files: {result}")
